DROP DATABASE TIENDA;
CREATE DATABASE TIENDA;
USE TIENDA;



CREATE TABLE Productos(Idproducto TINYINT (3) NOT NULL  PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR (15)  NOT NULL, Descripcion VARCHAR (60)  NOT NULL, Imagen VARCHAR(30)  NOT NULL,
Cantidad INT  NOT NULL , Valor_Unitario INT  NOT NULL) ENGINE=InnoDB DEFAULT  CHARSET=utf8mb4;

CREATE TABLE Produccion(Idproduccion TINYINT (3) PRIMARY KEY AUTO_INCREMENT , 
Fecha DATE , Producto TINYINT(3) ,Cantidad INT, 
FOREIGN KEY(Producto) REFERENCES Productos(Idproducto) ON DELETE SET NULL 
ON UPDATE CASCADE) ENGINE=InnoDB;


CREATE TABLE Ventas(Idventa TINYINT (3) PRIMARY KEY AUTO_INCREMENT,
Fecha DATE,Producto TINYINT (3),Cantidad INT,
Valor_Unitario INT,Valor_Total INT,
FOREIGN KEY(Producto) REFERENCES Productos(Idproducto) ON DELETE SET NULL 
ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE Compras(Idcompra TINYINT(3) PRIMARY KEY AUTO_INCREMENT,Fecha DATE, Producto TINYINT (3) ,
Cantidad INT, Valor_Unitario INT ,Valor_Total INT , FOREIGN KEY(Producto) REFERENCES Productos(Idproducto) ON DELETE SET NULL 
ON UPDATE CASCADE) ENGINE=InnoDB;
 

CREATE TABLE Gastos (Idgastos INT PRIMARY KEY AUTO_INCREMENT,
Fecha DATE, Producto TINYINT (3), Descripcion VARCHAR (30),Valor_Total INT, 
FOREIGN KEY(Producto) REFERENCES Productos(Idproducto) ON DELETE SET NULL 
ON UPDATE CASCADE)  ENGINE=InnoDB;



 


